#
quarkus.langchain4j.ollama.base-url=http://localhost:11434

quarkus.langchain4j.ollama.devservices.enabled=false

# Define o modelo a ser utilizado pelo Ollama, neste caso, o Llama 3.2 com 3 bilhões de parâmetros
quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:20b

# Define um timeout de 60 segundos para as requisições feitas ao Ollama
quarkus.langchain4j.ollama.timeout=60s

# Configura o caminho para os arquivos de RAG (Retrieval-Augmented Generation) utilizados pelo LangChain4j
# quarkus.langchain4j.easy-rag.path=me.rayll.src/main/resources/rag

# Define o modelo de embedding a ser utilizado pelo Ollama, neste caso, o Nomic Embedding Text
quarkus.langchain4j.ollama.embedding-model.model-id=nomic-embed-text

# Configura��es PGVector
quarkus.langchain4j.pgvector.register-vector-pg-extension=true
quarkus.langchain4j.pgvector.dimension=768
quarkus.langchain4j.pgvector.table=travel_embeddings
quarkus.langchain4j.pgvector.drop-table-first=true